# Basic Algebra

Syntax of Julia is similar to other language but there are few major differences

In [1]:
# Example 1

In [2]:
A = rand(1:4,4,4)

4×4 Matrix{Int64}:
 4  1  2  2
 4  4  3  3
 4  1  2  1
 1  3  2  4

In [3]:
B = A # Assigning A to B

4×4 Matrix{Int64}:
 4  1  2  2
 4  4  3  3
 4  1  2  1
 1  3  2  4

In [4]:
C = copy(A) # Copy A to C

4×4 Matrix{Int64}:
 4  1  2  2
 4  4  3  3
 4  1  2  1
 1  3  2  4

In [5]:
# Let's try to change an element of A
A[1] = 10

10

In [6]:
[B C]

4×8 Matrix{Int64}:
 10  1  2  2  4  1  2  2
  4  4  3  3  4  4  3  3
  4  1  2  1  4  1  2  1
  1  3  2  4  1  3  2  4

In [7]:
# While assigning is like pointing, so change is A make change in B 

In [8]:
# But copy is different so there's no change in C, creating a distinct object

# Basic Algebra Use and Defining

In [10]:
# Declaring of vector
x = ones(4)

4-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0

In [15]:
# Multiply a vector
b = A*x

4-element Vector{Float64}:
 15.0
 14.0
  8.0
 10.0

### Transposition of a Matrix

In [17]:
A' # for conjugate transpose

4×4 adjoint(::Matrix{Int64}) with eltype Int64:
 10  4  4  1
  1  4  1  3
  2  3  2  2
  2  3  1  4

In [19]:
transpose(A) # just the transpose

4×4 transpose(::Matrix{Int64}) with eltype Int64:
 10  4  4  1
  1  4  1  3
  2  3  2  2
  2  3  1  4

### Transpose Multiplication

In [20]:
A'A

4×4 Matrix{Int64}:
 133  33  42  40
  33  27  22  27
  42  22  21  23
  40  27  23  30

In [21]:
# No need to use * to get the transpose multiplication

### Solving Linear System

In [22]:
# Ax = b wherer square A is solved by \ function

In [23]:
A\b

4-element Vector{Float64}:
 1.0
 0.9999999999999998
 1.0000000000000002
 1.0

### Overdetermined Systems

In [24]:
Atall = rand(4,2)

4×2 Matrix{Float64}:
 0.467829  0.746173
 0.589026  0.098723
 0.829229  0.826985
 0.419386  0.662656

In [25]:
Atall\b

2-element Vector{Float64}:
 16.226752695905954
  2.114126811097189

# Factorisation