# Loops

### While Loops

In [103]:
#= julia
while *condition*
    *loop body*
end
=#

In [104]:
n = 5
while n < 10
    n += 1
    println(n)
end

6
7
8
9
10


In [105]:
# We can allo iterate over an array

In [106]:
myfriends = ["Kanhaiya", "Suman", "Kusum", "Utpal"]

4-element Vector{String}:
 "Kanhaiya"
 "Suman"
 "Kusum"
 "Utpal"

In [107]:
i = 1
while i <= length(myfriends)
    name = myfriends[i]
    println("Hello, $name, Great to see you!")
    i += 1
end

Hello, Kanhaiya, Great to see you!
Hello, Suman, Great to see you!
Hello, Kusum, Great to see you!
Hello, Utpal, Great to see you!


### For Loops

In [108]:
#=
for *var* in *loop iterable*
    *loop body*
end
=#

In [109]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [110]:
for friend in myfriends
    println("Hello $friend, How are you?")
end

Hello Kanhaiya, How are you?
Hello Suman, How are you?
Hello Kusum, How are you?
Hello Utpal, How are you?


#### Use of For Loop to create some tables

In [111]:
a,b = 10,10
X = zeros(a,b) 

10×10 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [112]:
for i in 1:a
    for j in 1:b
        X[i,j] = i + j
    end
end
# Example of a nested for loops

In [113]:
X

10×10 Matrix{Float64}:
  2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0
  3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0
  4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0
  5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0
  6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0
  7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0
  8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0
  9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0
 10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0
 11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0  20.0

In [114]:
# We can congest it further

In [115]:
Y = zeros(a,b)

10×10 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [116]:
for i in 1:a, j in 1:b
    Y[i,j] = i+j+1
end

In [117]:
Y

10×10 Matrix{Float64}:
  3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0
  4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0
  5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0
  6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0
  7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0
  8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0
  9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0
 10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0
 11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0  20.0
 12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0  20.0  21.0

In [118]:
# More Julian way is to use a array comprehension

In [119]:
Z = [i+j+2 for i in 1:6, j in 1:6]
# Array Comprehension

6×6 Matrix{Int64}:
 4   5   6   7   8   9
 5   6   7   8   9  10
 6   7   8   9  10  11
 7   8   9  10  11  12
 8   9  10  11  12  13
 9  10  11  12  13  14

In [120]:
# Show the exact loop with every step addition

In [121]:
for n in 1:10
    M = [i+j for i in 1:n, j in 1:n]
    display(M)
end

1×1 Matrix{Int64}:
 2

2×2 Matrix{Int64}:
 2  3
 3  4

3×3 Matrix{Int64}:
 2  3  4
 3  4  5
 4  5  6

4×4 Matrix{Int64}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Matrix{Int64}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Matrix{Int64}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Matrix{Int64}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20

# Conditionals

In [122]:
#=
if *conditions 1*
    *option 1*
elseif *conditions 2*
    *options 2*
else
    *options 3*
end
=#

In [123]:
name = "Bhupesh"
if length(name) < 6
    println("$name is a short name")
elseif length(name) > 10
    println("$name is a long name")
else
    println("$name is a perfect length name")
end

Bhupesh is a perfect length name


#### Use of ternary operator in Conditional Syntax

In [124]:
#=

a ? b : c

which is same as

if a
    b
else
    c
end

=#

In [125]:
x = 12
y = 15

15

In [126]:
if (x>y)
    x
else
    y
end

15

In [127]:
(x>y) ? x : y

15

#### Short Circuit Evaluation

In [128]:
# && - Similar to the R 

In [129]:
# a && b - Only runs when both the scenario is correct(True)

In [130]:
(x<y) && println("$x is smaller than $y")

12 is smaller than 15


In [131]:
(x>y) && println("$x is greater than $y")

false

# Declare a Functions

In [132]:
#=
function *function name* (*any arguments/variables given*)
    *body of functions*
end
=#

In [133]:
function area_of_circle(radius)
    (22/7)*radius^2
end

area_of_circle (generic function with 1 method)

In [134]:
area_of_circle(25)

1964.2857142857142

In [135]:
area_of_circle(1)

3.142857142857143

In [136]:
# New function to create area of rectangle
function rectangle(length,breadth)
    area = length*breadth
    println("Area of rectangle is equal to $area")
    perimeter = 2*(length+breadth)
    println("Perimeter of rectangle is equal to $perimeter")
end

rectangle (generic function with 1 method)

In [137]:
rectangle(10,5)

Area of rectangle is equal to 50
Perimeter of rectangle is equal to 30


### Declare function in a single line

In [138]:
#=
*function name*(*variables*) = *function body*
=#

In [139]:
square(number) = number^2

square (generic function with 1 method)

In [140]:
square(12)

144

In [141]:
square_root(number) = number^(1/2)

square_root (generic function with 1 method)

In [142]:
square_root(144)

12.0

### Declare functions as 'annonymus' functions

In [143]:
myname = name -> println("Hello $name")

#31 (generic function with 1 method)

In [144]:
myname("Poly")

Hello Poly


In [145]:
countdown = number -> [println(number-n) for n in 1:number]

#33 (generic function with 1 method)

In [146]:
countdown(5);

4
3
2
1
0


# Duck-typing in Julia

In [147]:
# Works on whatever input makes sense

In [148]:
myname(1234567890)

Hello 1234567890


In [149]:
# instead of string we gave a integer number but it still worked

In [150]:
# Similarly for square function

In [151]:
square(3)

9

In [152]:
square("Hello")

"HelloHello"

In [153]:
A = rand(4,4)

4×4 Matrix{Float64}:
 0.964785  0.565947   0.171537   0.138581
 0.721243  0.146593   0.0561761  0.703745
 0.883047  0.0520778  0.663936   0.817322
 0.959315  0.947985   0.674055   0.685763

In [154]:
square(A)

4×4 Matrix{Float64}:
 1.62341  0.769287  0.40459   0.767218
 1.52629  1.09974   0.643615  0.731631
 2.25987  1.31678   1.14613   1.26216
 2.86235  1.36709   1.12758   1.82127

In [155]:
B = rand(2,4)

2×4 Matrix{Float64}:
 0.492914  0.740205  0.508051  0.675695
 0.488582  0.504462  0.181318  0.211265

In [157]:
square(B)
# We get an error because matrix multiplication is not possible with uneven dimensions

LoadError: DimensionMismatch("A has dimensions (2,4) but B has dimensions (2,4)")

In [158]:
C = rand(5)

5-element Vector{Float64}:
 0.2098081851945417
 0.8074838068620291
 0.5503023653379819
 0.013860828312232787
 0.323760789076287

In [159]:
square(C)

LoadError: MethodError: no method matching ^(::Vector{Float64}, ::Int64)
Closest candidates are:
  ^(::Union{AbstractChar, AbstractString}, ::Integer) at strings/basic.jl:718
  ^(::Complex{var"#s79"} where var"#s79"<:AbstractFloat, ::Integer) at complex.jl:818
  ^(::Complex{var"#s79"} where var"#s79"<:Integer, ::Integer) at complex.jl:820
  ...

# Mutating vs Non-Mutating Functions

In [160]:
#=

Functions followed by ! at the end alter the contents

Functions not followed by ! does not alter the contents

=#

In [161]:
#= Example

sort

sort! (sort bang)

=#

In [163]:
newlist = [9,1,8,2,7,3,6,4,5];

In [164]:
# Apply non mutating functions
sort(newlist)

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [166]:
# Re checking the original list
newlist
#No change to the original list

9-element Vector{Int64}:
 9
 1
 8
 2
 7
 3
 6
 4
 5

In [167]:
# Applying the mutating functions
sort!(newlist)

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [168]:
# Checking the original list
newlist
# Contents has been altered

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

# Broadcasting

In [169]:
#=
Two type of functions with use of .
f() => treat the variable/input object as one single element
f.() => broadcast over the elements of the variable/input object
=#

In [170]:
# Example
# Create an array for that

In [171]:
AB = [i+3*j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [172]:
#Let's use the square function on this array

In [173]:
square(AB)
# Whole matrix is multiplied by itself

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [174]:
square.(AB)
# Every element of the matrix is multiplied with itself

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [ ]:
Si