# Loops

### While Loops

In [2]:
#= julia
while *condition*
    *loop body*
end
=#

In [3]:
n = 5
while n < 10
    n += 1
    println(n)
end

6
7
8
9
10


In [4]:
# We can allo iterate over an array

In [5]:
myfriends = ["Kanhaiya", "Suman", "Kusum", "Utpal"]

4-element Vector{String}:
 "Kanhaiya"
 "Suman"
 "Kusum"
 "Utpal"

In [6]:
i = 1
while i <= length(myfriends)
    name = myfriends[i]
    println("Hello, $name, Great to see you!")
    i += 1
end

Hello, Kanhaiya, Great to see you!
Hello, Suman, Great to see you!
Hello, Kusum, Great to see you!
Hello, Utpal, Great to see you!


### For Loops

In [7]:
#=
for *var* in *loop iterable*
    *loop body*
end
=#

In [8]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [9]:
for friend in myfriends
    println("Hello $friend, How are you?")
end

Hello Kanhaiya, How are you?
Hello Suman, How are you?
Hello Kusum, How are you?
Hello Utpal, How are you?


#### Use of For Loop to create some tables

In [10]:
a,b = 10,10
X = zeros(a,b) 

10×10 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [11]:
for i in 1:a
    for j in 1:b
        X[i,j] = i + j
    end
end
# Example of a nested for loops

In [12]:
X

10×10 Matrix{Float64}:
  2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0
  3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0
  4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0
  5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0
  6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0
  7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0
  8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0
  9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0
 10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0
 11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0  20.0

In [13]:
# We can congest it further

In [14]:
Y = zeros(a,b)

10×10 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [15]:
for i in 1:a, j in 1:b
    Y[i,j] = i+j+1
end

In [16]:
Y

10×10 Matrix{Float64}:
  3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0
  4.0   5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0
  5.0   6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0
  6.0   7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0
  7.0   8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0
  8.0   9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0
  9.0  10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0
 10.0  11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0
 11.0  12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0  20.0
 12.0  13.0  14.0  15.0  16.0  17.0  18.0  19.0  20.0  21.0

In [17]:
# More Julian way is to use a array comprehension

In [18]:
Z = [i+j+2 for i in 1:6, j in 1:6]
# Array Comprehension

6×6 Matrix{Int64}:
 4   5   6   7   8   9
 5   6   7   8   9  10
 6   7   8   9  10  11
 7   8   9  10  11  12
 8   9  10  11  12  13
 9  10  11  12  13  14

In [19]:
# Show the exact loop with every step addition

In [20]:
for n in 1:10
    M = [i+j for i in 1:n, j in 1:n]
    display(M)
end

1×1 Matrix{Int64}:
 2

2×2 Matrix{Int64}:
 2  3
 3  4

3×3 Matrix{Int64}:
 2  3  4
 3  4  5
 4  5  6

4×4 Matrix{Int64}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Matrix{Int64}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Matrix{Int64}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Matrix{Int64}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20

# Conditionals

In [21]:
#=
if *conditions 1*
    *option 1*
elseif *conditions 2*
    *options 2*
else
    *options 3*
end
=#

In [22]:
name = "Bhupesh"
if length(name) < 6
    println("$name is a short name")
elseif length(name) > 10
    println("$name is a long name")
else
    println("$name is a perfect length name")
end

Bhupesh is a perfect length name


#### Use of ternary operator in Conditional Syntax

In [23]:
#=

a ? b : c

which is same as

if a
    b
else
    c
end

=#

In [24]:
x = 12
y = 15

15

In [25]:
if (x>y)
    x
else
    y
end

15

In [26]:
(x>y) ? x : y

15

#### Short Circuit Evaluation

In [27]:
# && - Similar to the R 

In [28]:
# a && b - Only runs when both the scenario is correct(True)

In [29]:
(x<y) && println("$x is smaller than $y")

12 is smaller than 15


In [30]:
(x>y) && println("$x is greater than $y")

false

# Declare a Functions

In [31]:
#=
function *function name* (*any arguments/variables given*)
    *body of functions*
end
=#

In [32]:
function area_of_circle(radius)
    (22/7)*radius^2
end

area_of_circle (generic function with 1 method)

In [33]:
area_of_circle(25)

1964.2857142857142

In [34]:
area_of_circle(1)

3.142857142857143

In [35]:
# New function to create area of rectangle
function rectangle(length,breadth)
    area = length*breadth
    println("Area of rectangle is equal to $area")
    perimeter = 2*(length+breadth)
    println("Perimeter of rectangle is equal to $perimeter")
end

rectangle (generic function with 1 method)

In [36]:
rectangle(10,5)

Area of rectangle is equal to 50
Perimeter of rectangle is equal to 30


### Declare function in a single line

In [37]:
#=
*function name*(*variables*) = *function body*
=#

In [38]:
square(number) = number^2

square (generic function with 1 method)

In [39]:
square(12)

144

In [40]:
square_root(number) = number^(1/2)

square_root (generic function with 1 method)

In [41]:
square_root(144)

12.0

### Declare functions as 'annonymus' functions

In [42]:
myname = name -> println("Hello $name")

#5 (generic function with 1 method)

In [43]:
myname("Poly")

Hello Poly


In [44]:
countdown = number -> [println(number-n) for n in 1:number]

#7 (generic function with 1 method)

In [45]:
countdown(5);

4
3
2
1
0


# Duck-typing in Julia

In [46]:
# Works on whatever input makes sense

In [47]:
myname(1234567890)

Hello 1234567890


In [48]:
# instead of string we gave a integer number but it still worked

In [49]:
# Similarly for square function

In [50]:
square(3)

9

In [51]:
square("Hello")

"HelloHello"

In [52]:
A = rand(4,4)

4×4 Matrix{Float64}:
 0.558218  0.165041  0.287209  0.845777
 0.630001  0.551475  0.794353  0.849436
 0.772991  0.782979  0.647965  0.440859
 0.478537  0.302354  0.331397  0.189214

In [53]:
square(A)

4×4 Matrix{Float64}:
 1.04233   0.663748  0.757816  0.898972
 1.71962   1.28689   1.41522   1.51221
 1.63661   1.20001   1.40993   1.68795
 0.804325  0.562405  0.655055  0.843467

In [54]:
B = rand(2,4)

2×4 Matrix{Float64}:
 0.571556  0.479907  0.99083   0.875494
 0.32626   0.727508  0.405608  0.381162

In [55]:
square(B)
# We get an error because matrix multiplication is not possible with uneven dimensions

LoadError: DimensionMismatch("A has dimensions (2,4) but B has dimensions (2,4)")

In [56]:
C = rand(5)

5-element Vector{Float64}:
 0.9429239555229112
 0.7668877502952745
 0.3355903707090553
 0.6009631681750971
 0.13222935398596625

In [57]:
square(C)

LoadError: MethodError: no method matching ^(::Vector{Float64}, ::Int64)
Closest candidates are:
  ^(::Union{AbstractChar, AbstractString}, ::Integer) at strings/basic.jl:718
  ^(::Complex{var"#s79"} where var"#s79"<:AbstractFloat, ::Integer) at complex.jl:818
  ^(::Complex{var"#s79"} where var"#s79"<:Integer, ::Integer) at complex.jl:820
  ...

# Mutating vs Non-Mutating Functions

In [58]:
#=

Functions followed by ! at the end alter the contents

Functions not followed by ! does not alter the contents

=#

In [59]:
#= Example

sort

sort! (sort bang)

=#

In [60]:
newlist = [9,1,8,2,7,3,6,4,5];

In [61]:
# Apply non mutating functions
sort(newlist)

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [62]:
# Re checking the original list
newlist
#No change to the original list

9-element Vector{Int64}:
 9
 1
 8
 2
 7
 3
 6
 4
 5

In [63]:
# Applying the mutating functions
sort!(newlist)

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [64]:
# Checking the original list
newlist
# Contents has been altered

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

# Broadcasting

In [65]:
#=
Two type of functions with use of .
f() => treat the variable/input object as one single element
f.() => broadcast over the elements of the variable/input object
=#

In [66]:
# Example
# Create an array for that

In [67]:
AB = [i+3*j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [68]:
#Let's use the square function on this array

In [69]:
square(AB)
# Whole matrix is multiplied by itself

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [70]:
square.(AB)
# Every element of the matrix is multiplied with itself

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

# Exercises 

In [71]:
### Exercises
#
# #### 4.1
# Loop over integers between 1 and 100 and print their squares.
# 

In [72]:
for n in 1:100
    println(n^2)
end

1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576
625
676
729
784
841
900
961
1024
1089
1156
1225
1296
1369
1444
1521
1600
1681
1764
1849
1936
2025
2116
2209
2304
2401
2500
2601
2704
2809
2916
3025
3136
3249
3364
3481
3600
3721
3844
3969
4096
4225
4356
4489
4624
4761
4900
5041
5184
5329
5476
5625
5776
5929
6084
6241
6400
6561
6724
6889
7056
7225
7396
7569
7744
7921
8100
8281
8464
8649
8836
9025
9216
9409
9604
9801
10000


In [73]:
# #### 4.2
# Add to the code above a bit to create a dictionary, `squares` that holds integers and
# their squares as key, value pairs such that
#
# ```julia
# squares[10] == 100
# ```
# 

In [74]:
squares = Dict()

Dict{Any, Any}()

In [75]:
for n in 1:100
    squares[n] = n^2
end

In [76]:
squares[10]

100

In [77]:
@assert squares[10] == 100

In [78]:
@assert squares[11] == 121

In [79]:
# #### 4.3
# Use an array comprehension to create an an array `squares_arr` that stores the squares for
# all integers between 1 and 100.
# 

In [81]:
squares_arr = [n^2 for n in 1:100];

In [82]:
# #### 5.1
# Write a conditional statement that prints a number if the number is even and the string
# "odd" if the number is odd.
# 

In [86]:
x =5

5

In [87]:
if x%2 == 0
    println(x)
else
    println("odd")
end

odd


In [88]:
(x%2==0) ? x : "odd"

"odd"

In [90]:

# ### Exercises
#
# #### 6.1
# Write a function `add_one` that adds 1 to its input.
# 

In [91]:
function add_one(x)
    x+1
end

add_one (generic function with 1 method)

In [92]:
@assert add_one(1) == 2

In [93]:
@assert add_one(11) == 12

In [94]:
# #### 6.2
# Use `map` or `broadcast` to increment every element of matrix `A` by `1` and assign it to
# a variable `A1`.
# 

In [114]:
A = fill(1:9,(3, 3))

3×3 Matrix{UnitRange{Int64}}:
 1:9  1:9  1:9
 1:9  1:9  1:9
 1:9  1:9  1:9

In [107]:
A1 = map(add_one,A)

3×3 Matrix{Float64}:
 1.45423  1.03492  1.808
 1.63561  1.88343  1.2406
 1.47626  1.23036  1.07258

In [108]:
A2 = add_one.(A1)

3×3 Matrix{Float64}:
 2.45423  2.03492  2.808
 2.63561  2.88343  2.2406
 2.47626  2.23036  2.07258

In [109]:
# #### 6.3
# Use the broadcast dot syntax to increment every element of matrix `A1` by `1` and store it
# in variable `A2`
# 

In [110]:
@assert A2 == [3 4 5; 6 7 8;9 10 11]

LoadError: AssertionError: A2 == [3 4 5; 6 7 8; 9 10 11]